[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin-explorer = "1.2.20"
chrono = { version = "0.4.31", features = ["serde"] }
color-eyre = "0.6.2"
itertools = "0.12.0"
rayon = "1.8.0"
reqwest = { version = "0.11.22", features = [ "blocking", "json" ] }
serde = { version = "1.0.193", features = [ "derive", "rc" ] }
serde_json = "1.0.108"
