[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin-explorer = "1.2.20"
chrono = "0.4.31"
color-eyre = "0.6.2"
itertools = "0.11.0"
nohash-hasher = "0.2.0"
rayon = "1.8.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.188", features = [ "derive", "rc" ] }
serde_json = "1.0.107"
