[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
bitcoin-explorer = "1.2.20"
chrono = { version = "0.4.31", features = ["serde"] }
color-eyre = "0.6.2"
indexmap = { version = "2.1.0", features = ["serde"] }
itertools = "0.12.0"
memory-stats = "1.1.0"
nohash-hasher = "0.2.0"
rayon = "1.8.0"
reqwest = { version = "0.11.22", features = [ "blocking", "json" ] }
rustc-hash = "1.1.0"
serde = { version = "1.0.193", features = [ "derive", "rc" ] }
serde_json = "1.0.108"
