[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2.0.0-rc.3", features = ["std"] }
bitcoin-explorer = "1.2.20"
bitcoin_hashes = { version = "0.10.0" }
chrono = { version = "0.4.31", features = [ "serde", "rkyv" ] }
color-eyre = "0.6.2"
itertools = "0.12.0"
postcard = "1.0.8"
rayon = "1.8.0"
reqwest = { version = "0.11.22", features = [ "blocking", "json" ] }
serde = { version = "1.0.193", features = [ "derive" ] }
serde_json = "1.0.108"
