[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bincode = "2.0.0-rc.3"
bincode = { git = "https://github.com/bincode-org/bincode.git" }
bitcoin = "0.31.1"
bitcoin_hashes = { version = "0.13.0" }
byteorder = "1.5.0"
chrono = { version = "0.4.33", features = [ "serde", "rkyv" ] }
color-eyre = "0.6.2"
db-key = "=0.0.5"
derive_deref = "1.1.1"
itertools = "0.12.0"
leveldb = "0.8.6"
ordered-float = "4.2.0"
par-iter-sync = "0.1.11"
rayon = "1.8.1"
reqwest = { version = "0.11.23", features = [ "blocking", "json" ] }
sanakirja = "1.3.3"
serde = { version = "1.0.195", features = [ "derive" ] }
serde_json = "1.0.111"
